# Generated by Django 3.1.7 on 2021-04-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeTask_api', '0002_auto_20210406_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedhometask',
            name='home_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='homeTask_api.hometask'),
            preserve_default=False,
        ),
    ]
