# Generated by Django 3.1.7 on 2021-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeTask_api', '0004_remove_hometask_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedhometask',
            name='status',
            field=models.CharField(default='Выполнено', max_length=150, verbose_name='Статус'),
        ),
    ]
