# Generated by Django 3.1.7 on 2021-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeTask_api', '0005_checkedhometask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedhometask',
            name='status',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default=0, max_length=150, verbose_name='Статус'),
        ),
    ]
