# Generated by Django 3.1.7 on 2021-04-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeTask_api', '0006_auto_20210407_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedhometask',
            name='status',
        ),
        migrations.AddField(
            model_name='checkedhometask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AddField(
            model_name='checkedhometask',
            name='is_evaluated',
            field=models.BooleanField(default=False, verbose_name='Оценено'),
        ),
    ]
