# Generated by Django 3.1.7 on 2021-03-24 19:08

from django.db import migrations, models
import test_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('topic', models.CharField(choices=[(test_api.models.TestTopic['IT'], 'IT'), (test_api.models.TestTopic['BUSINESS'], 'Business'), (test_api.models.TestTopic['SCHOOL'], 'SCHOOL')], max_length=150)),
                ('required_score', models.IntegerField(verbose_name='Нужное количество баллов')),
                ('difficulty', models.CharField(choices=[(test_api.models.TestTopic['IT'], 'IT'), (test_api.models.TestTopic['BUSINESS'], 'Business'), (test_api.models.TestTopic['SCHOOL'], 'SCHOOL')], default=1, max_length=100, verbose_name='Сложность теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
