# Generated by Django 3.1.7 on 2021-03-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_category_newanswer_newquestion_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(blank=True, to='test_api.NewQuestion'),
        ),
    ]
