# Generated by Django 3.1.7 on 2021-03-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0005_auto_20210329_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='newquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newquestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='NewAnswer',
        ),
        migrations.DeleteModel(
            name='NewQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
