# Generated by Django 3.1.7 on 2021-04-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0007_auto_20210331_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test', 'created'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
